# Generated by Django 4.1.7 on 2023-05-04 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("enderecos", "0003_remove_endereco_user"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_endereco",
                to="enderecos.endereco",
            ),
        ),
    ]
