# Generated by Django 4.1.7 on 2023-05-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cpf",
            field=models.IntegerField(max_length=11, unique=True),
        ),
    ]
