# Generated by Django 4.1.7 on 2023-05-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_cpf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cpf",
            field=models.PositiveBigIntegerField(max_length=11, unique=True),
        ),
    ]
