# Generated by Django 4.1.7 on 2023-05-03 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_user_cpf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cpf",
            field=models.PositiveBigIntegerField(
                unique=True,
                validators=[
                    django.core.validators.MaxLengthValidator(11),
                    django.core.validators.MinLengthValidator(11),
                ],
            ),
        ),
    ]
