# Generated by Django 4.1.7 on 2023-05-03 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_alter_user_cpf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cpf",
            field=models.PositiveBigIntegerField(
                unique=True,
                validators=[
                    django.core.validators.MaxValueValidator(99999999999),
                    django.core.validators.MinValueValidator(11111111111),
                ],
            ),
        ),
    ]
