# Generated by Django 4.1.7 on 2023-05-03 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("descricao", models.TextField(max_length=255)),
                (
                    "img",
                    models.URLField(
                        default="https://as1.ftcdn.net/v2/jpg/05/04/28/96/1000_F_504289605_zehJiK0tCuZLP2MdfFBpcJdOVxKLnXg1.jpg",
                        max_length=255,
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=8)),
                ("quantidade_estoque", models.IntegerField()),
                ("vendidos", models.IntegerField(default=0)),
                (
                    "categorias",
                    models.CharField(
                        choices=[
                            ("Informática", "Informatica"),
                            ("Eletrodomésticos", "Eletrodomesticos"),
                            ("Casa", "Casa"),
                            ("Livros", "Livros"),
                            ("Eletrônicos", "Eletronicos"),
                            ("Games", "Games"),
                            ("Brinquedos", "Brinquedos"),
                            ("Crianças", "Criancas"),
                            ("Not Informed", "Default"),
                        ],
                        default="Not Informed",
                        max_length=127,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="produtos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
