# Generated by Django 4.1.7 on 2023-05-04 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("produtos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="produtos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
