# Generated by Django 4.1.7 on 2023-05-03 19:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("produtos", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="produto",
            old_name="user",
            new_name="vendedor",
        ),
    ]
