# Generated by Django 4.1.7 on 2023-05-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produtos", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="disponibilidade",
            field=models.BooleanField(default=True),
        ),
    ]
