# Generated by Django 4.1.7 on 2023-05-04 17:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("produtos", "0003_produto_disponibilidade"),
    ]

    operations = [
        migrations.RenameField(
            model_name="produto",
            old_name="categorias",
            new_name="categoria",
        ),
    ]
