# Generated by Django 4.1.7 on 2023-05-04 18:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("produtos", "0004_rename_categorias_produto_categoria"),
    ]

    operations = [
        migrations.RenameField(
            model_name="produto",
            old_name="categoria",
            new_name="categorias",
        ),
    ]
