# Generated by Django 4.1.7 on 2023-05-05 13:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pedidos", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pedido",
            old_name="user_id",
            new_name="user",
        ),
    ]
