# Generated by Django 4.1.7 on 2023-05-04 14:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("enderecos", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="endereco",
            name="user",
        ),
    ]
