# Generated by Django 4.1.7 on 2023-05-05 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("carrinhos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carrinhoproduto",
            name="carrinho",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carrinho_produto_carrinhos",
                to="carrinhos.carrinho",
            ),
        ),
    ]
